name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Deploy only on pushes to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build Project
        run: npm run build  # Adjust if your project uses a different build command

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.0
        with:
          publish-dir: ./build  # Replace with your build output directory (e.g., `dist` for Angular)
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Add this in GitHub Secrets
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}        # Add this in GitHub Secrets
